[workspace]
members = ["proc_macros"]

[package]
name = "mchprs"
version = "0.3.0"
authors = ["StackDoubleFlow <ojaslandge@gmail.com>"]
edition = "2018"
description = "A multithreaded minecraft server built for redstone."
readme = "README.md"
license = "MIT"
keywords = ["minecraft", "server", "redstone"]
repository = "https://github.com/MCHPR/MCHPRS"
homepage = "https://github.com/MCHPR/MCHPRS"

[profile.release]
debug = true

include = [
    "**/*.rs",
    "Cargo.toml",
]

[badges]
travis-ci = { repository = "StackDoubleFlow/MCHPRS" }

[dev-dependencies]
criterion = "0.3.4"

[[bench]]
name = "bitbuffer"
harness = false

[dependencies]
mchprs_proc_macros = { path = "./proc_macros" }
toml = "0.5.8"
flate2 = "1.0.20"
byteorder = "1.4.2"
hematite-nbt = "0.5.1"
bitflags = "1.2.1"
serde = "1.0.123"
md5 = "0.7.0"
bus = "2.2.3"
serde_json = "1.0.62"
bincode = "1.3.1"
ctrlc = { version = "3.1.7", features = ["termination"] }
log = "0.4.14"
fern = { version = "0.6.0", features = ["colored"] }
chrono = "0.4"
rand = "0.8.3"
regex = "1.4.3"
backtrace = "0.3.56"
rusqlite = { version="0.25.3", features=["bundled"] }
anyhow = "1.0"
rayon = "1.5"
cranelift = { version = "0.76", optional = true }
cranelift-jit  = { version = "0.76", optional = true }
cranelift-module  = { version = "0.76", optional = true }
toml_edit = "0.2.0"
mysql = "21.0.0"

[features]
jit_cranelift = ["cranelift", "cranelift-jit", "cranelift-module"]
